module.exports.hobbies = [
    'Model',
    'Plastic',
    'Tabletop',
    'Board Game',
    'Card',
    'Robot',
    'Toy',
    'Golf',
    'Paintball',
    'Train',
    'War',
    'Comic',
    'Laser',
    'Plane',
    'Ship',
    'Drone',
    'Tank',
    'Art',
    'Airbrushing',
    '3D Printing',
    'Animation',
    'Beatboxing',
    'Beer Tasting',
    'Scupting',
    'Scuba Diving',
    'Scrapbooking',
    'Ceramics',
    'Caligraphy',
    'Craft',
    'Cosplaying',
    'Mechanics',
    'Karaoke',
    'Martial Arts',
    'Mazes',
    'Ice Skating',
    'Skating',
    'Electronics',
    'Gunsmithing',
    'Swordfighting',
    'Powerlifting',
    'Robotics',
    'Cybernetics'
]

module.exports.places = [
    'Supplies',
    'Lobby',
    'Depot',
    'Stop',
    'Spot',
    'Union',
    'Territory',
    'Zone',
    'Warehouse',
    'Base',
    'Wonders',
    'Collectibles',
    'Workshop',
    'Supply',
    'Warehouse',
    'Solution',
    'Store',
    'World',
    'Union',
    'Place',
    'Land',
    'Outlet',
    'Addiction'
]

module.exports.descriptors = [
    'Cosmic',
    'Ultimate',
    'Unlimited',
    'Ultra',
    'Speed',
    'Total',
    'Ancient',
    'Definitive',
    'Pure',
    'My',
    'Best',
    'Dune',
    'Arctic',
    'Discount',
    'Classic',
    'The',
    'Star',
    'Amazing',
    'Stellar'
]

module.exports.images = [
    
]